"""Typed Pydantic models for LLM outputs in analyst-agent-service (§10.5).

Mirrors the models in interviewer-agent-service for cross-service consistency.
Both services should import AnalystReport and TrainingPreset from here.
"""

from typing import Any, Dict, List, Literal, Optional, Union
from datetime import datetime
from pydantic import BaseModel, Field, field_validator


class AnswerEvaluation(BaseModel):
    """Per-question evaluation as recorded by interviewer-agent-service.

    Analyst uses this to compute the final report score.
    Mirrors interviewer-agent-service/src/models/llm_outputs.py.
    """

    completeness_score: float = Field(ge=0.0, le=1.0)
    accuracy_score: float = Field(ge=0.0, le=1.0)
    overall_score: float = Field(ge=0.0, le=1.0)
    decision: Literal["next", "hint", "clarify", "redirect", "skip"]
    missing_points: List[str] = Field(default_factory=list)
    strong_points: List[str] = Field(default_factory=list)
    feedback: str = ""
    decision_confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    reasoning: str = ""


class ErrorEntry(BaseModel):
    """Single error entry in errors_by_topic."""
    question: str = ""
    error: str = ""
    correction: str = ""


class AnalystReport(BaseModel):
    """Structured report generated by analyst-agent-service (§10.5).

    Replaces the manual key-list validation in validate_report() with full
    Pydantic v2 validation. Use model_json_schema() to inject the schema
    into the LLM system prompt.
    """

    summary: str = Field(min_length=10)
    score: int = Field(ge=0, le=100)
    errors_by_topic: Dict[str, List[Union[ErrorEntry, str]]] = Field(default_factory=dict)
    strengths: List[str] = Field(default_factory=list)
    preparation_plan: List[str] = Field(default_factory=list)
    materials: List[str] = Field(default_factory=list)

    @field_validator("score", mode="before")
    @classmethod
    def clamp_score(cls, v: int) -> int:
        return max(0, min(100, int(v)))


class TrainingPreset(BaseModel):
    """Training/study preset generated for a user (§10.5)."""

    target_mode: Literal["study", "training"]
    topic: str
    weak_topics: List[str] = Field(default_factory=list)
    recommended_materials: List[str] = Field(default_factory=list)
    priority: int = Field(ge=1, le=3, default=2)


class ProgressDelta(BaseModel):
    """Comparison of a topic score between sessions (§10.6)."""

    topic: str
    previous_score: float = Field(ge=0.0, le=1.0)
    current_score: float = Field(ge=0.0, le=1.0)
    delta: float
    assessment: Literal["improved", "same", "declined"]
