{{- if and (index .Values.services "agent-service").enabled (index .Values.services "agent-service").autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tensor-talks.fullname" . }}-agent-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "tensor-talks.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tensor-talks.fullname" . }}-agent-service
  minReplicas: {{ (index .Values.services "agent-service").autoscaling.minReplicas }}
  maxReplicas: {{ (index .Values.services "agent-service").autoscaling.maxReplicas }}
  metrics:
    {{- if (index .Values.services "agent-service").autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ (index .Values.services "agent-service").autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if (index .Values.services "agent-service").autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ (index .Values.services "agent-service").autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
