apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tensor-talks-github-repo
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-tensor-talks
    kind: SecretStore
  target:
    name: tensor-talks-repo
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        type: Z2l0
        url: aHR0cHM6Ly9naXRodWIuY29tL1BhdWxSeWNoa292L1RlbnNvclRhbGtzLmdpdA==
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  data:
    - secretKey: username
      remoteRef:
        key: tensor-talks/github
        property: username
    - secretKey: password
      remoteRef:
        key: tensor-talks/github
        property: token
