apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-tensor-talks
  namespace: argocd
spec:
  provider:
    vault:
      server: http://tensor-talks-vault.tensor-talks:8200
      path: kv
      version: v2
      auth:
        # Для локального Vault используем токен
        tokenSecretRef:
          name: tensor-talks-vault
          key: root-token
