server:
  host: "0.0.0.0"
  port: 8083

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  ttl_hours: 24

session_crud:
  base_url: "http://session-crud-service:8085"
  timeout_seconds: 5

kafka:
  brokers: ["kafka:9092"]
  topic_request: "tensor-talks-interview.build.request"
  topic_response: "tensor-talks-interview.build.response"
  consumer_group: "tensor-talks-session-manager-service-group"

session_manager:
  max_active_sessions: 100
  program_timeout_seconds: 30  # Таймаут ожидания программы интервью от builder-service (для HTTP ответа bff-service)
