"""Typed Pydantic models for LLM outputs (§10.5).

All LLM responses should be validated through these models instead of raw
Dict[str, Any]. Provides runtime validation, JSON Schema generation for
prompt injection, and static type safety.
"""

from typing import Dict, List, Literal, Optional
from pydantic import BaseModel, Field, field_validator


class AnswerEvaluation(BaseModel):
    """Structured evaluation of a candidate's answer (§10.5, §10.7).

    Used in evaluate_answer node and stored in QuestionEvaluation.
    """

    completeness_score: float = Field(
        ge=0.0, le=1.0, description="How complete the answer is (0-1)"
    )
    accuracy_score: float = Field(
        ge=0.0, le=1.0, description="How accurate/correct the answer is (0-1)"
    )
    overall_score: float = Field(
        ge=0.0, le=1.0, description="Aggregate score (0-1)"
    )
    decision: Literal["next", "hint", "clarify", "redirect", "skip"] = Field(
        description="Agent's branching decision"
    )
    missing_points: List[str] = Field(
        default_factory=list,
        description="Key points missing from the answer",
    )
    strong_points: List[str] = Field(
        default_factory=list,
        description="What the candidate answered correctly",
    )
    feedback: str = Field(
        default="",
        description="Internal feedback (not shown to candidate)",
    )
    # Confidence fields (§10.7)
    decision_confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description=(
            "Agent's confidence in the decision. 0.5 = borderline, 1.0 = certain. "
            "Values below 0.5 trigger re-evaluation."
        ),
    )
    reasoning: str = Field(
        default="",
        description=(
            "Brief reasoning for the decision (1-2 sentences). "
            "Used for tracing and eval; never shown to the user."
        ),
    )

    @field_validator("overall_score", mode="before")
    @classmethod
    def clamp_overall_score(cls, v: float) -> float:
        return max(0.0, min(1.0, float(v)))


class OffTopicClassification(BaseModel):
    """Classification of user message relevance (§10.5)."""

    classification: Literal["on_topic", "off_topic", "comment"] = Field(
        description="Whether the message is on-topic, off-topic, or a neutral comment"
    )
    reason: str = Field(default="", description="Brief explanation of the classification")


class PIICheckResult(BaseModel):
    """Result of PII detection check (§10.5, §10.11)."""

    contains_pii: bool = Field(
        description="Whether the text contains personally identifiable information"
    )
    reason: str = Field(default="", description="Brief explanation if PII detected")
    masked_text: str = Field(
        default="",
        description="Text with PII fragments replaced by type placeholders (e.g. [имя], [компания])",
    )


class AnalystReport(BaseModel):
    """Structured report generated by analyst-agent-service (§10.5).

    Replaces the manual dict-based report structure with full Pydantic validation.
    """

    summary: str = Field(
        min_length=10,
        description="Executive summary of the interview session",
    )
    score: int = Field(ge=0, le=100, description="Overall score 0-100")
    errors_by_topic: Dict[str, List[str]] = Field(
        default_factory=dict,
        description="Mapping of topic → list of errors/gaps identified",
    )
    strengths: List[str] = Field(
        min_length=1,
        description="List of candidate's strong points",
    )
    preparation_plan: List[str] = Field(
        min_length=1,
        description="Recommended preparation steps",
    )
    materials: List[str] = Field(
        default_factory=list,
        description="Recommended study materials (URLs or titles)",
    )

    @field_validator("score", mode="before")
    @classmethod
    def clamp_score(cls, v: int) -> int:
        return max(0, min(100, int(v)))


class TrainingPreset(BaseModel):
    """Training/study preset generated by analyst-agent-service (§10.5)."""

    target_mode: Literal["study", "training"] = Field(
        description="Whether the preset is for study or practice"
    )
    topic: str = Field(description="Primary topic for this preset")
    weak_topics: List[str] = Field(
        default_factory=list,
        description="Topics the candidate needs to improve",
    )
    recommended_materials: List[str] = Field(
        default_factory=list,
        description="Materials to study before starting this preset",
    )
    priority: int = Field(
        ge=1, le=3, default=2,
        description="Preset priority: 1 = high, 2 = medium, 3 = low",
    )
