{{- if and .Values.postgresql.deployment.enabled .Values.postgresql.pgadmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tensor-talks.fullname" . }}-pgadmin
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "tensor-talks.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.pgadmin.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tensor-talks.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
{{- end }}
